# Generated by Django 2.1.2 on 2019-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_T',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('ukey', models.CharField(blank=True, max_length=20)),
                ('credential_id', models.CharField(blank=True, max_length=250)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('pub_key', models.CharField(blank=True, max_length=65)),
                ('sign_count', models.IntegerField(blank=True)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('rp_id', models.CharField(blank=True, max_length=253)),
                ('icon_url', models.CharField(blank=True, max_length=2083)),
            ],
        ),
    ]
